version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: my-task-def
        LoadBalancerInfo:
          ContainerName: my-container
          ContainerPort: 80
